name: 'Branch Storage Action'
description: 'Saves files (e.g: badges) from GitHub actions on a dedicated branch to serve a static storage.'

branding:
  icon: "save"
  color: "blue"

inputs:
  storage-branch:
    description: "Name of the branch that will be used for storage"
    required: false
    default: 'gh-storage'
  prune:
    description: "If true, deletes as well as adds or updates files, otherwise only adds"
    required: false
    default: false
  src:
    description: "Path to the file that will be saved"
    required: true
  dst:
    description: "Path in storage branch where the file will be saved"
    required: true
  comment:
    description: "Commit message associated with this modification in storage branch"
    required: false
    default: Update storage contents
  username:
    description: "Username that will appear in history applying changes to the storage branch"
    required: false
    default: Branch Storage Action
  useremail:
    description: "Email address that will appear in history applying changes to the storage branch"
    required: false
    default: branch.storage@github.action

runs:
  
  using: "composite"
  
  steps: 
    - shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        src: "${{inputs.src}}"
        dst: "${{inputs.dst}}"
        comment: "${{inputs.comment}}"
        storage_branch: "${{inputs.storage-branch}}"
        prune: "${{inputs.prune}}"
        username: "${{inputs.username}}"
        useremail: "${{inputs.useremail}}"
