name: 'Static files storage'
description: 'Saves files (e.g: badges) from GitHub actions on a dedicated branch to serve a static storage.'

inputs:
  storage-branch:
    description: "Name of the branch that will be used for storage"
    required: false
    default: 'gh-storage'
  src:
    description: "Path to the file that will be saved"
    required: true
  dst:
    description: "Path in storage branch where the file will be saved"
    required: true

runs:
  
  using: "composite"
  
  steps: 
    - shell: bash
      run: |
        git config user.email storage@github.action
        git config user.name "GitHub storage action"
      
    - name: Create temporary copy of file to save
      shell: bash
      run: |
        cp -r ${{inputs.src}} /tmp/artifact
    
    - name: Create storage branch if not exists, and checkout
      shell: bash
      run: |
        (git branch --remote | grep origin/${{ inputs.storage-branch }} >/dev/null && (git checkout ${{ inputs.storage-branch }} && echo "Checked out storage branch!" || echo "Unable to checkout storage branch")) \
          || (${{ github.action_path }}/scripts/create-storage-branch.sh ${{ inputs.storage-branch }} && echo "Storage branch created!")
          
    - name: Copy tmp file to destination file
      shell: bash
      run: |
        folder=$(dirname ${{inputs.dst}})
        mkdir -p $folder || echo Unable to create destination folder
        mv /tmp/artifacts ${{inputs.dst}}
