name: 'Static files storage'
description: 'Saves files (e.g: badges) from GitHub actions on a dedicated branch to serve a static storage.'

inputs:
  storage-branch:
    description: "Name of the branch that will be used for storage"
    required: false
    default: 'gh-storage'
  src:
    description: "Path to the file that will be saved"
    required: true
  dst:
    description: "Path in storage branch where the file will be saved"
    required: true
  comment:
    description: "Commit message associated with this modification in storage branch"
    required: false
    default: Update a file

runs:
  
  using: "composite"
  
  steps: 
    - shell: bash
      run: ${{ github.action_path }}/action.sh
      env:
        src: "${{inputs.src}}"
        dst: "${{inputs.dst}}"
        comment: "${{inputs.comment}}"
        storage_branch: "${{inputs.storage-branch}}"
