name: 'Static files storage'
description: 'Saves files (e.g: badges) from GitHub actions on a dedicated branch to serve a static storage.'

inputs:
  storage-branch:
    description: 'Name of the branch that will be used for storage'
    required: false
    default: 'gh-storage'
  artifacts:
    description: 'List of files and destination in storage with sturcture [{src: "...", dst: "..."}]'
    required: true
    default: []

runs:
  using: "composite"
  
  strategy:
    matrix:
      artifact: ${{inputs.artifacts}} 
  
  steps: 
    - shell: bash
      run: echo Save file ${file_src} to ${{ file_dst }} on branch ${{ inputs.storage_branch }}.
      env:
        file_src: ${{matrix.artifact.src}}
        file_dst: ${{matrix.artifact.dst}}
    
    - shell: bash
      run: |
        (git branch --remote | grep origin/${{ inputs.storage_branch }} >1 && echo storage branch found) || echo storage branch not found
      
